<ul class="elitteh-side-nav">
  <li class="side-nav-title"><span>Зерноочистительные комплексы</span></li>
        <li><a href="/kz-25">КЗ–25</a></li>
        <li><a href="/kz-50">КЗ–50</a></li>
  <li class="side-nav-title"><span>Зерноочистительные сепараторы</span></li>
        <li><a href="/bcs25">БЦС–25</a></li>
        <li><a href="/bcs50">БЦС–50</a></li>
        <li><a href="/sad">САД</a></li>
        <li><a href="/ovs-25">ОВС–25</a></li>
        <li><a href="/b32-o">БЗ2–О</a></li>
  <li class="side-nav-title"><span>Зерносушилки</span></li>
        <li><a href="/dryers_for_wood">Зерносушилки на дровах</a></li>
  <li class="side-nav-title"><span>Транспортное оборудование</span></li>
        <li><a href="/norii">Нории</a></li>
  <li class="side-nav-title"><span>Погрузочное навесное оборудование</span></li>
        <li><a href="/snu-550">СНУ–550</a></li>
        <li><a href="/pku-08">ПКУ–0,8</a></li>
        <li><a href="/pbm-800">ПБМ–800</a></li>
  <li class="side-nav-title"><span>Зернометатели и зернопогрузчики</span></li>
        <li><a href="/zm-100">ЗМ–100</a></li>
        <li><a href="/zm-60">ЗМ–60</a></li>
        <li><a href="/kshp">КШП</a></li>
</ul>